package com.application.smartstation.ui.model

class LoginResponse(var status:Boolean, var message:String,var otp:Int,var statuscode:Int)
class OTPVerifyResponse(var status:Boolean, var message:String,var data:DataOtp)
class DataOtp(var id:String, var name:String, var email: String, var about:String, var phone:String, var login_status:String, var company_name:String, var company_mail:String,var country:String, var profile_pic:String, var deviceType:String, var deviceToken:String, var accessToken:String, var status:String, var security_status:String)
class ProfileUpdateResponse(var status:Boolean, var message:String, var user_id:String, var data:DataProfile)
class DataProfile(var id:String, var name:String, var phone:String, var company_name:String, var company_mail:String,var country:String, var profile_pic:String, var deviceType:String, var deviceToken:String, var accessToken:String, var status:String, var email:String, var about:String)
class ImageUploadResponse(var status: Boolean, var imageurl:String, var message:String)
class TermsResponse(var status: Boolean, var imageurl:String, var message:String, var terms:String)
class ChangeNotification(var status: Boolean,var statuscode:Int, var message:String, var notification_status:String, var sound:String, var vibration:String)
class BaseResponse(var status:Boolean, var message:String, var statuscode:String, var filepath:String)
class UpdateProfilePicResponse(var status:Boolean, var message:String, var statuscode:String, var profile_pic:String)
class EditProfileResponse(var status:Boolean, var message:String, var statuscode:String, var name:String, var email:String, var about:String)
class GetSignatureResponse(var status: Boolean,var message: String, var data:ArrayList<SignatureListData>)
class SignatureListData(var id:String, var name: String, var image:String)
class GetTFAResponse(var status:Boolean, var message:String, var statuscode:String,var secret_key:String,var tfa_status:String)
class GetChatListResponse(var status:Boolean, var message:String, var data:ArrayList<DataChatList>)
class DataChatList(var id:String, var date:String, var message:String, var message_type:String, var unread_message:String, var userid:String, var name:String, var profile:String, var room:String, var chat_type:String)
class GetMailListResponse(var status:Boolean, var message:String, var data:ArrayList<DataMailList>)
class DataMailList(var id:String, var user_id:String, var datetime:String, var subject:String, var body:String, var mail_read_status:String, var profile_pic:String)
class GetUserListResponse(var status:Boolean, var message:String, var data:ArrayList<DataUserList>)
class DataUserList(var user_id:String, var name:String, var profile_pic:String, var about:String, var statusSelected:Boolean = false, var alreadySelected:Boolean = false)
class GetChatDetailsListResponse(var status:Boolean, var message:String, var data:ChatListRes)
class ChatListRes(var list:ArrayList<ChatDetailsRes>)
class ChatDetailsRes(var id:String, var date:String, var senter_id:String, var receiver_id:String, var message:String, var message_type:String, var message_status:String, var room:String, var type:String, var name:String)
class OnlineRes(var status:Boolean, var message:String,var statuscode:String, var online_status:String, var last_seen:String)
class TypingRes(var status:Boolean, var message:String,var statuscode:String, var typing:String, var user_id:String)
class GrpUserListRes(var status:Boolean, var message:String,var statuscode:String,var group_name:String, var group_profile:String, var number_of_members:String, var data:ArrayList<UserListGrp>)
class UserListGrp(var user_id: String, var username:String, var type:String, var about:String, var profile_pic:String)


class SendMsgResponse(var status:Boolean, var message:String)
class PostResponse(var ip:String)
class CountryList(var countryCode:String, var countryNum:String,var countryName:String)
class Person(var name:String,var email:String)
class ChatResponse(var title:String, var sub:String, var time:String, var date:String, var profile:Int, var status:Int)
class ChatHisResponse(var data:ArrayList<DataResChat>)
class DataResChat(var date:String,var type:String, var msgType:String, var msg:String, var time:String, var imgUrl:Int, var readStatus:Int)